### PR TITLE
`raise ValueError, 'Time less than 0'` throws a tuple of an exception class object and text, not an exception object

### PR DESCRIPTION
**Pull request by kaiidams**
Use `raise Value(...)` to throw an exception.

### CODE REVIEW

**Comment by kylebgorman** [comment]
Thanks, I think this is an improvement. Aren't the outer parentheses next to `raise` redundant though?

**Comment by kaiidams** [comment]
You're right. The outer parentheses next to raise are redundant in Python. All the other `raise`s also have parentheses, they should be removed altogether. Do we want to remove other parentheses in this pull request?

**Comment by kylebgorman** [comment]
Could you just remove the outermost ones on the `raise` expressions? If you
can do that we can then merge. No need to worry about any other (extraneous
or otherwise) parens. Thanks!

**Comment by kaiidams** [comment]
@kylebgorman Replaced

**Review by kylebgorman — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
